apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/horsedb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: horse-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: horse-mongo
  template:
    metadata:
      labels:
        app: horse-mongo
    spec:
      containers:
        - name: horse-mongo
          image: mongo
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/ton
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: horse-mongo-srv
spec:
  selector:
    app: horse-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017